IP_NETWORK="192.168.69."
WORKSTATION_IP=10

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box_check_update = false
  config.vm.define "workstation" do |workstation|
    workstation.vm.box = "ubuntu/jammy64"
    workstation.vm.hostname = "workstation"
    workstation.vm.network "private_network", ip: IP_NETWORK + "#{WORKSTATION_IP}"
    workstation.vm.provider :virtualbox do |v|
      v.memory = 4096
      v.name = "workstation"
      v.cpus = 2
    end
    workstation.vm.provision "updates", type: "shell", run: "never" do |s|
      s.path = "scripts/updates.sh"
    end
    workstation.vm.provision "upgrades", type: "shell", run: "never" do |s|
      s.path = "scripts/upgrades.sh"
    end
    workstation.vm.provision "webapp", type: "shell", run: "never" do |s|
      s.path = "scripts/webapp.sh"
    end
    workstation.vm.provision "bootstrap", type: "shell", run: "never" do |s|
      s.inline = "echo 'bootstrapping'"
    end
  end
end
