Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box_check_update = false
  config.vm.define "workstation" do |workstation|
    workstation.vm.box = "ubuntu/jammy64"
    workstation.vm.provider :virtualbox do |v|
      v.memory = 1024
      v.name = "workstation"
      v.cpus = 2
    end
    workstation.vm.provision :shell, :inline => "sudo apt update; sudo apt upgrade -y", run: "always"
    workstation.vm.provision :ansible_local do |ansible|
      ansible.playbook = "/vagrant/playbooks/master.yml"
      ansible.install = true
      ansible.inventory_path = "/vagrant/inventory"
      ansible.config_file = "/vagrant/ansible.cfg"
      ansible.limit = "all"
    end
  end
end
