Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box_check_update = false
  config.vm.define "workstation" do |workstation|
    workstation.vm.box = "ubuntu/jammy64"
    workstation.vm.provider :virtualbox do |v|
      v.memory = 2048
      v.name = "workstation"
      v.cpus = 2
    end
    workstation.vm.provision :shell, :inline => "sudo apt update; sudo apt upgrade -y", run: "always"
  end
end
